@echo off
REM This file was generated by auto-py-to-exe.
pyinstaller --noconfirm --onefile --windowed --icon "C:\Users\Fuck-Windows\Downloads\package\icon.ico" --clean --log-level "INFO" --optimize "1" --add-binary "C:\Users\Fuck-Windows\Downloads\package\icon.ico;."  "C:\Users\Fuck-Windows\Downloads\package\generate_discord_viewer.py"
pause
