@echo off
REM This file was generated by auto-py-to-exe.
pyinstaller --noconfirm --onefile --windowed --icon "D:\Projects\discord_package_viewer\icon.ico" --clean --log-level "INFO" --optimize "1" --add-binary "D:\Projects\discord_package_viewer\icon.ico;."  "D:\Projects\discord_package_viewer\generate_discord_viewer.py"
pause
